/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRegisterRouteImport } from './routes/invite-register'
import { Route as HostedRouteImport } from './routes/hosted'
import { Route as FoundaryRouteImport } from './routes/foundary'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostedIndexRouteImport } from './routes/hosted/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as HostedTicketsRouteImport } from './routes/hosted/tickets'
import { Route as HostedTeamRouteImport } from './routes/hosted/team'
import { Route as HostedRequestFundsRouteImport } from './routes/hosted/request-funds'
import { Route as HostedPerksRouteImport } from './routes/hosted/perks'
import { Route as HostedApplicationsRouteImport } from './routes/hosted/applications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRegisterRoute = InviteRegisterRouteImport.update({
  id: '/invite-register',
  path: '/invite-register',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedRoute = HostedRouteImport.update({
  id: '/hosted',
  path: '/hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundaryRoute = FoundaryRouteImport.update({
  id: '/foundary',
  path: '/foundary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedIndexRoute = HostedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedTicketsRoute = HostedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => HostedRoute,
} as any)
const HostedTeamRoute = HostedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => HostedRoute,
} as any)
const HostedRequestFundsRoute = HostedRequestFundsRouteImport.update({
  id: '/request-funds',
  path: '/request-funds',
  getParentRoute: () => HostedRoute,
} as any)
const HostedPerksRoute = HostedPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => HostedRoute,
} as any)
const HostedApplicationsRoute = HostedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => HostedRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/foundary': typeof FoundaryRoute
  '/hosted': typeof HostedRouteWithChildren
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/perks': typeof HostedPerksRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/hosted/': typeof HostedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foundary': typeof FoundaryRoute
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/perks': typeof HostedPerksRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin': typeof AdminIndexRoute
  '/hosted': typeof HostedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/foundary': typeof FoundaryRoute
  '/hosted': typeof HostedRouteWithChildren
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/perks': typeof HostedPerksRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/hosted/': typeof HostedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/foundary'
    | '/hosted'
    | '/invite-register'
    | '/login'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/perks'
    | '/hosted/request-funds'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin/'
    | '/hosted/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foundary'
    | '/invite-register'
    | '/login'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/perks'
    | '/hosted/request-funds'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin'
    | '/hosted'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/foundary'
    | '/hosted'
    | '/invite-register'
    | '/login'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/perks'
    | '/hosted/request-funds'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin/'
    | '/hosted/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FoundaryRoute: typeof FoundaryRoute
  HostedRoute: typeof HostedRouteWithChildren
  InviteRegisterRoute: typeof InviteRegisterRoute
  LoginRoute: typeof LoginRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-register': {
      id: '/invite-register'
      path: '/invite-register'
      fullPath: '/invite-register'
      preLoaderRoute: typeof InviteRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted': {
      id: '/hosted'
      path: '/hosted'
      fullPath: '/hosted'
      preLoaderRoute: typeof HostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundary': {
      id: '/foundary'
      path: '/foundary'
      fullPath: '/foundary'
      preLoaderRoute: typeof FoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/': {
      id: '/hosted/'
      path: '/'
      fullPath: '/hosted/'
      preLoaderRoute: typeof HostedIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/tickets': {
      id: '/hosted/tickets'
      path: '/tickets'
      fullPath: '/hosted/tickets'
      preLoaderRoute: typeof HostedTicketsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/team': {
      id: '/hosted/team'
      path: '/team'
      fullPath: '/hosted/team'
      preLoaderRoute: typeof HostedTeamRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/request-funds': {
      id: '/hosted/request-funds'
      path: '/request-funds'
      fullPath: '/hosted/request-funds'
      preLoaderRoute: typeof HostedRequestFundsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/perks': {
      id: '/hosted/perks'
      path: '/perks'
      fullPath: '/hosted/perks'
      preLoaderRoute: typeof HostedPerksRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/applications': {
      id: '/hosted/applications'
      path: '/applications'
      fullPath: '/hosted/applications'
      preLoaderRoute: typeof HostedApplicationsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HostedRouteChildren {
  HostedApplicationsRoute: typeof HostedApplicationsRoute
  HostedPerksRoute: typeof HostedPerksRoute
  HostedRequestFundsRoute: typeof HostedRequestFundsRoute
  HostedTeamRoute: typeof HostedTeamRoute
  HostedTicketsRoute: typeof HostedTicketsRoute
  HostedIndexRoute: typeof HostedIndexRoute
}

const HostedRouteChildren: HostedRouteChildren = {
  HostedApplicationsRoute: HostedApplicationsRoute,
  HostedPerksRoute: HostedPerksRoute,
  HostedRequestFundsRoute: HostedRequestFundsRoute,
  HostedTeamRoute: HostedTeamRoute,
  HostedTicketsRoute: HostedTicketsRoute,
  HostedIndexRoute: HostedIndexRoute,
}

const HostedRouteWithChildren =
  HostedRoute._addFileChildren(HostedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FoundaryRoute: FoundaryRoute,
  HostedRoute: HostedRouteWithChildren,
  InviteRegisterRoute: InviteRegisterRoute,
  LoginRoute: LoginRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
