/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeRouteImport } from './routes/se'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as NyheterIndexRouteImport } from './routes/nyheter/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as NyheterSlugRouteImport } from './routes/nyheter/$slug'
import { Route as EnTeamRouteImport } from './routes/en/team'
import { Route as EnRulesRouteImport } from './routes/en/rules'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStadgarRouteImport } from './routes/admin/stadgar'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminAvtalRouteImport } from './routes/admin/avtal'
import { Route as AdminAvgangRouteImport } from './routes/admin/avgang'
import { Route as PublicTeamRouteImport } from './routes/_public/team'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as EnNyheterIndexRouteImport } from './routes/en/nyheter/index'
import { Route as EnBlogsIndexRouteImport } from './routes/en/blogs/index'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin/tickets/index'
import { Route as EnNyheterSlugRouteImport } from './routes/en/nyheter/$slug'
import { Route as EnBlogsSlugRouteImport } from './routes/en/blogs/$slug'
import { Route as AdminTicketsTypesRouteImport } from './routes/admin/tickets/types'
import { Route as AdminTicketsScanRouteImport } from './routes/admin/tickets/scan'
import { Route as AdminTicketsNewRouteImport } from './routes/admin/tickets/new'
import { Route as AdminTicketsEventsRouteImport } from './routes/admin/tickets/events'
import { Route as AdminEditIdRouteImport } from './routes/admin/edit/$id'
import { Route as PublicBiljettCodeRouteImport } from './routes/_public/biljett/$code'

const SeRoute = SeRouteImport.update({
  id: '/se',
  path: '/se',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const NyheterIndexRoute = NyheterIndexRouteImport.update({
  id: '/nyheter/',
  path: '/nyheter/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const NyheterSlugRoute = NyheterSlugRouteImport.update({
  id: '/nyheter/$slug',
  path: '/nyheter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTeamRoute = EnTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => EnRoute,
} as any)
const EnRulesRoute = EnRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStadgarRoute = AdminStadgarRouteImport.update({
  id: '/stadgar',
  path: '/stadgar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvtalRoute = AdminAvtalRouteImport.update({
  id: '/avtal',
  path: '/avtal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvgangRoute = AdminAvgangRouteImport.update({
  id: '/avgang',
  path: '/avgang',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNyheterIndexRoute = EnNyheterIndexRouteImport.update({
  id: '/nyheter/',
  path: '/nyheter/',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogsIndexRoute = EnBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => EnRoute,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AdminRoute,
} as any)
const EnNyheterSlugRoute = EnNyheterSlugRouteImport.update({
  id: '/nyheter/$slug',
  path: '/nyheter/$slug',
  getParentRoute: () => EnRoute,
} as any)
const EnBlogsSlugRoute = EnBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => EnRoute,
} as any)
const AdminTicketsTypesRoute = AdminTicketsTypesRouteImport.update({
  id: '/tickets/types',
  path: '/tickets/types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsScanRoute = AdminTicketsScanRouteImport.update({
  id: '/tickets/scan',
  path: '/tickets/scan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsNewRoute = AdminTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsEventsRoute = AdminTicketsEventsRouteImport.update({
  id: '/tickets/events',
  path: '/tickets/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const PublicBiljettCodeRoute = PublicBiljettCodeRouteImport.update({
  id: '/biljett/$code',
  path: '/biljett/$code',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/hello': typeof ApiHelloRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/privacy': typeof PublicPrivacyRoute
  '/rules': typeof PublicRulesRoute
  '/team': typeof PublicTeamRoute
  '/admin/avgang': typeof AdminAvgangRoute
  '/admin/avtal': typeof AdminAvtalRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/stadgar': typeof AdminStadgarRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/en/': typeof EnIndexRoute
  '/nyheter/': typeof NyheterIndexRoute
  '/biljett/$code': typeof PublicBiljettCodeRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/en/blogs/$slug': typeof EnBlogsSlugRoute
  '/en/nyheter/$slug': typeof EnNyheterSlugRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/en/blogs/': typeof EnBlogsIndexRoute
  '/en/nyheter/': typeof EnNyheterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/hello': typeof ApiHelloRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/privacy': typeof PublicPrivacyRoute
  '/rules': typeof PublicRulesRoute
  '/team': typeof PublicTeamRoute
  '/admin/avgang': typeof AdminAvgangRoute
  '/admin/avtal': typeof AdminAvtalRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/stadgar': typeof AdminStadgarRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/en': typeof EnIndexRoute
  '/nyheter': typeof NyheterIndexRoute
  '/biljett/$code': typeof PublicBiljettCodeRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/en/blogs/$slug': typeof EnBlogsSlugRoute
  '/en/nyheter/$slug': typeof EnNyheterSlugRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/en/blogs': typeof EnBlogsIndexRoute
  '/en/nyheter': typeof EnNyheterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/_api/hello': typeof ApiHelloRoute
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/rules': typeof PublicRulesRoute
  '/_public/team': typeof PublicTeamRoute
  '/admin/avgang': typeof AdminAvgangRoute
  '/admin/avtal': typeof AdminAvtalRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/stadgar': typeof AdminStadgarRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/en/': typeof EnIndexRoute
  '/nyheter/': typeof NyheterIndexRoute
  '/_public/biljett/$code': typeof PublicBiljettCodeRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/en/blogs/$slug': typeof EnBlogsSlugRoute
  '/en/nyheter/$slug': typeof EnNyheterSlugRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/en/blogs/': typeof EnBlogsIndexRoute
  '/en/nyheter/': typeof EnNyheterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/en'
    | '/login'
    | '/se'
    | '/hello'
    | '/example-protected-route'
    | '/privacy'
    | '/rules'
    | '/team'
    | '/admin/avgang'
    | '/admin/avtal'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/stadgar'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/privacy'
    | '/en/rules'
    | '/en/team'
    | '/nyheter/$slug'
    | '/verify/$code'
    | '/admin/'
    | '/blogs/'
    | '/en/'
    | '/nyheter/'
    | '/biljett/$code'
    | '/admin/edit/$id'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/en/blogs/$slug'
    | '/en/nyheter/$slug'
    | '/admin/tickets/'
    | '/en/blogs/'
    | '/en/nyheter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/se'
    | '/hello'
    | '/example-protected-route'
    | '/privacy'
    | '/rules'
    | '/team'
    | '/admin/avgang'
    | '/admin/avtal'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/stadgar'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/privacy'
    | '/en/rules'
    | '/en/team'
    | '/nyheter/$slug'
    | '/verify/$code'
    | '/admin'
    | '/blogs'
    | '/en'
    | '/nyheter'
    | '/biljett/$code'
    | '/admin/edit/$id'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/en/blogs/$slug'
    | '/en/nyheter/$slug'
    | '/admin/tickets'
    | '/en/blogs'
    | '/en/nyheter'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/admin'
    | '/en'
    | '/login'
    | '/se'
    | '/_api/hello'
    | '/_protected/example-protected-route'
    | '/_public/privacy'
    | '/_public/rules'
    | '/_public/team'
    | '/admin/avgang'
    | '/admin/avtal'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/stadgar'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/privacy'
    | '/en/rules'
    | '/en/team'
    | '/nyheter/$slug'
    | '/verify/$code'
    | '/_public/'
    | '/admin/'
    | '/blogs/'
    | '/en/'
    | '/nyheter/'
    | '/_public/biljett/$code'
    | '/admin/edit/$id'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/en/blogs/$slug'
    | '/en/nyheter/$slug'
    | '/admin/tickets/'
    | '/en/blogs/'
    | '/en/nyheter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  LoginRoute: typeof LoginRoute
  SeRoute: typeof SeRoute
  ApiHelloRoute: typeof ApiHelloRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  NyheterSlugRoute: typeof NyheterSlugRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  NyheterIndexRoute: typeof NyheterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/se': {
      id: '/se'
      path: '/se'
      fullPath: '/se'
      preLoaderRoute: typeof SeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyheter/': {
      id: '/nyheter/'
      path: '/nyheter'
      fullPath: '/nyheter/'
      preLoaderRoute: typeof NyheterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyheter/$slug': {
      id: '/nyheter/$slug'
      path: '/nyheter/$slug'
      fullPath: '/nyheter/$slug'
      preLoaderRoute: typeof NyheterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/team': {
      id: '/en/team'
      path: '/team'
      fullPath: '/en/team'
      preLoaderRoute: typeof EnTeamRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/rules': {
      id: '/en/rules'
      path: '/rules'
      fullPath: '/en/rules'
      preLoaderRoute: typeof EnRulesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stadgar': {
      id: '/admin/stadgar'
      path: '/stadgar'
      fullPath: '/admin/stadgar'
      preLoaderRoute: typeof AdminStadgarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avtal': {
      id: '/admin/avtal'
      path: '/avtal'
      fullPath: '/admin/avtal'
      preLoaderRoute: typeof AdminAvtalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avgang': {
      id: '/admin/avgang'
      path: '/avgang'
      fullPath: '/admin/avgang'
      preLoaderRoute: typeof AdminAvgangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nyheter/': {
      id: '/en/nyheter/'
      path: '/nyheter'
      fullPath: '/en/nyheter/'
      preLoaderRoute: typeof EnNyheterIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blogs/': {
      id: '/en/blogs/'
      path: '/blogs'
      fullPath: '/en/blogs/'
      preLoaderRoute: typeof EnBlogsIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/nyheter/$slug': {
      id: '/en/nyheter/$slug'
      path: '/nyheter/$slug'
      fullPath: '/en/nyheter/$slug'
      preLoaderRoute: typeof EnNyheterSlugRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/blogs/$slug': {
      id: '/en/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/en/blogs/$slug'
      preLoaderRoute: typeof EnBlogsSlugRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/tickets/types': {
      id: '/admin/tickets/types'
      path: '/tickets/types'
      fullPath: '/admin/tickets/types'
      preLoaderRoute: typeof AdminTicketsTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/scan': {
      id: '/admin/tickets/scan'
      path: '/tickets/scan'
      fullPath: '/admin/tickets/scan'
      preLoaderRoute: typeof AdminTicketsScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/new': {
      id: '/admin/tickets/new'
      path: '/tickets/new'
      fullPath: '/admin/tickets/new'
      preLoaderRoute: typeof AdminTicketsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/events': {
      id: '/admin/tickets/events'
      path: '/tickets/events'
      fullPath: '/admin/tickets/events'
      preLoaderRoute: typeof AdminTicketsEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/biljett/$code': {
      id: '/_public/biljett/$code'
      path: '/biljett/$code'
      fullPath: '/biljett/$code'
      preLoaderRoute: typeof PublicBiljettCodeRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRulesRoute: typeof PublicRulesRoute
  PublicTeamRoute: typeof PublicTeamRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBiljettCodeRoute: typeof PublicBiljettCodeRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRulesRoute: PublicRulesRoute,
  PublicTeamRoute: PublicTeamRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBiljettCodeRoute: PublicBiljettCodeRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAvgangRoute: typeof AdminAvgangRoute
  AdminAvtalRoute: typeof AdminAvtalRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminStadgarRoute: typeof AdminStadgarRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
  AdminTicketsEventsRoute: typeof AdminTicketsEventsRoute
  AdminTicketsNewRoute: typeof AdminTicketsNewRoute
  AdminTicketsScanRoute: typeof AdminTicketsScanRoute
  AdminTicketsTypesRoute: typeof AdminTicketsTypesRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvgangRoute: AdminAvgangRoute,
  AdminAvtalRoute: AdminAvtalRoute,
  AdminNewRoute: AdminNewRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminStadgarRoute: AdminStadgarRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
  AdminTicketsEventsRoute: AdminTicketsEventsRoute,
  AdminTicketsNewRoute: AdminTicketsNewRoute,
  AdminTicketsScanRoute: AdminTicketsScanRoute,
  AdminTicketsTypesRoute: AdminTicketsTypesRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnRulesRoute: typeof EnRulesRoute
  EnTeamRoute: typeof EnTeamRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBlogsSlugRoute: typeof EnBlogsSlugRoute
  EnNyheterSlugRoute: typeof EnNyheterSlugRoute
  EnBlogsIndexRoute: typeof EnBlogsIndexRoute
  EnNyheterIndexRoute: typeof EnNyheterIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnPrivacyRoute: EnPrivacyRoute,
  EnRulesRoute: EnRulesRoute,
  EnTeamRoute: EnTeamRoute,
  EnIndexRoute: EnIndexRoute,
  EnBlogsSlugRoute: EnBlogsSlugRoute,
  EnNyheterSlugRoute: EnNyheterSlugRoute,
  EnBlogsIndexRoute: EnBlogsIndexRoute,
  EnNyheterIndexRoute: EnNyheterIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  LoginRoute: LoginRoute,
  SeRoute: SeRoute,
  ApiHelloRoute: ApiHelloRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  NyheterSlugRoute: NyheterSlugRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  NyheterIndexRoute: NyheterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
