/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRegisterRouteImport } from './routes/invite-register'
import { Route as HostedRouteImport } from './routes/hosted'
import { Route as FoundaryRouteImport } from './routes/foundary'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostedIndexRouteImport } from './routes/hosted/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as HostedTicketsRouteImport } from './routes/hosted/tickets'
import { Route as HostedTeamRouteImport } from './routes/hosted/team'
import { Route as HostedSettingsRouteImport } from './routes/hosted/settings'
import { Route as HostedRequestFundsRouteImport } from './routes/hosted/request-funds'
import { Route as HostedPerksHubRouteImport } from './routes/hosted/perks-hub'
import { Route as HostedFaqRouteImport } from './routes/hosted/faq'
import { Route as HostedApplicationsRouteImport } from './routes/hosted/applications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminStoragePerksRouteImport } from './routes/admin/storage-perks'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as HostedPerksStorageRouteImport } from './routes/hosted/perks/storage'
import { Route as HostedPerksStorageUploadRouteImport } from './routes/hosted/perks/storage/upload'
import { Route as HostedPerksStorageLimitsRouteImport } from './routes/hosted/perks/storage/limits'
import { Route as HostedPerksStorageExplorerRouteImport } from './routes/hosted/perks/storage/explorer'
import { Route as HostedPerksStorageCdnRouteImport } from './routes/hosted/perks/storage/cdn'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRegisterRoute = InviteRegisterRouteImport.update({
  id: '/invite-register',
  path: '/invite-register',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedRoute = HostedRouteImport.update({
  id: '/hosted',
  path: '/hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundaryRoute = FoundaryRouteImport.update({
  id: '/foundary',
  path: '/foundary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedIndexRoute = HostedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedTicketsRoute = HostedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => HostedRoute,
} as any)
const HostedTeamRoute = HostedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => HostedRoute,
} as any)
const HostedSettingsRoute = HostedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HostedRoute,
} as any)
const HostedRequestFundsRoute = HostedRequestFundsRouteImport.update({
  id: '/request-funds',
  path: '/request-funds',
  getParentRoute: () => HostedRoute,
} as any)
const HostedPerksHubRoute = HostedPerksHubRouteImport.update({
  id: '/perks-hub',
  path: '/perks-hub',
  getParentRoute: () => HostedRoute,
} as any)
const HostedFaqRoute = HostedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => HostedRoute,
} as any)
const HostedApplicationsRoute = HostedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => HostedRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoragePerksRoute = AdminStoragePerksRouteImport.update({
  id: '/storage-perks',
  path: '/storage-perks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const HostedPerksStorageRoute = HostedPerksStorageRouteImport.update({
  id: '/perks/storage',
  path: '/perks/storage',
  getParentRoute: () => HostedRoute,
} as any)
const HostedPerksStorageUploadRoute =
  HostedPerksStorageUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => HostedPerksStorageRoute,
  } as any)
const HostedPerksStorageLimitsRoute =
  HostedPerksStorageLimitsRouteImport.update({
    id: '/limits',
    path: '/limits',
    getParentRoute: () => HostedPerksStorageRoute,
  } as any)
const HostedPerksStorageExplorerRoute =
  HostedPerksStorageExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => HostedPerksStorageRoute,
  } as any)
const HostedPerksStorageCdnRoute = HostedPerksStorageCdnRouteImport.update({
  id: '/cdn',
  path: '/cdn',
  getParentRoute: () => HostedPerksStorageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/foundary': typeof FoundaryRoute
  '/hosted': typeof HostedRouteWithChildren
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/storage-perks': typeof AdminStoragePerksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/faq': typeof HostedFaqRoute
  '/hosted/perks-hub': typeof HostedPerksHubRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/settings': typeof HostedSettingsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/hosted/': typeof HostedIndexRoute
  '/hosted/perks/storage': typeof HostedPerksStorageRouteWithChildren
  '/hosted/perks/storage/cdn': typeof HostedPerksStorageCdnRoute
  '/hosted/perks/storage/explorer': typeof HostedPerksStorageExplorerRoute
  '/hosted/perks/storage/limits': typeof HostedPerksStorageLimitsRoute
  '/hosted/perks/storage/upload': typeof HostedPerksStorageUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/foundary': typeof FoundaryRoute
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/storage-perks': typeof AdminStoragePerksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/faq': typeof HostedFaqRoute
  '/hosted/perks-hub': typeof HostedPerksHubRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/settings': typeof HostedSettingsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin': typeof AdminIndexRoute
  '/hosted': typeof HostedIndexRoute
  '/hosted/perks/storage': typeof HostedPerksStorageRouteWithChildren
  '/hosted/perks/storage/cdn': typeof HostedPerksStorageCdnRoute
  '/hosted/perks/storage/explorer': typeof HostedPerksStorageExplorerRoute
  '/hosted/perks/storage/limits': typeof HostedPerksStorageLimitsRoute
  '/hosted/perks/storage/upload': typeof HostedPerksStorageUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/foundary': typeof FoundaryRoute
  '/hosted': typeof HostedRouteWithChildren
  '/invite-register': typeof InviteRegisterRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/storage-perks': typeof AdminStoragePerksRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/hosted/applications': typeof HostedApplicationsRoute
  '/hosted/faq': typeof HostedFaqRoute
  '/hosted/perks-hub': typeof HostedPerksHubRoute
  '/hosted/request-funds': typeof HostedRequestFundsRoute
  '/hosted/settings': typeof HostedSettingsRoute
  '/hosted/team': typeof HostedTeamRoute
  '/hosted/tickets': typeof HostedTicketsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/hosted/': typeof HostedIndexRoute
  '/hosted/perks/storage': typeof HostedPerksStorageRouteWithChildren
  '/hosted/perks/storage/cdn': typeof HostedPerksStorageCdnRoute
  '/hosted/perks/storage/explorer': typeof HostedPerksStorageExplorerRoute
  '/hosted/perks/storage/limits': typeof HostedPerksStorageLimitsRoute
  '/hosted/perks/storage/upload': typeof HostedPerksStorageUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/foundary'
    | '/hosted'
    | '/invite-register'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/storage-perks'
    | '/admin/tickets'
    | '/admin/transfers'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/faq'
    | '/hosted/perks-hub'
    | '/hosted/request-funds'
    | '/hosted/settings'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin/'
    | '/hosted/'
    | '/hosted/perks/storage'
    | '/hosted/perks/storage/cdn'
    | '/hosted/perks/storage/explorer'
    | '/hosted/perks/storage/limits'
    | '/hosted/perks/storage/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/foundary'
    | '/invite-register'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/storage-perks'
    | '/admin/tickets'
    | '/admin/transfers'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/faq'
    | '/hosted/perks-hub'
    | '/hosted/request-funds'
    | '/hosted/settings'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin'
    | '/hosted'
    | '/hosted/perks/storage'
    | '/hosted/perks/storage/cdn'
    | '/hosted/perks/storage/explorer'
    | '/hosted/perks/storage/limits'
    | '/hosted/perks/storage/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/foundary'
    | '/hosted'
    | '/invite-register'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/admin/applications'
    | '/admin/logs'
    | '/admin/storage-perks'
    | '/admin/tickets'
    | '/admin/transfers'
    | '/admin/users'
    | '/hosted/applications'
    | '/hosted/faq'
    | '/hosted/perks-hub'
    | '/hosted/request-funds'
    | '/hosted/settings'
    | '/hosted/team'
    | '/hosted/tickets'
    | '/verify/$code'
    | '/admin/'
    | '/hosted/'
    | '/hosted/perks/storage'
    | '/hosted/perks/storage/cdn'
    | '/hosted/perks/storage/explorer'
    | '/hosted/perks/storage/limits'
    | '/hosted/perks/storage/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  FoundaryRoute: typeof FoundaryRoute
  HostedRoute: typeof HostedRouteWithChildren
  InviteRegisterRoute: typeof InviteRegisterRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TosRoute: typeof TosRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-register': {
      id: '/invite-register'
      path: '/invite-register'
      fullPath: '/invite-register'
      preLoaderRoute: typeof InviteRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted': {
      id: '/hosted'
      path: '/hosted'
      fullPath: '/hosted'
      preLoaderRoute: typeof HostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundary': {
      id: '/foundary'
      path: '/foundary'
      fullPath: '/foundary'
      preLoaderRoute: typeof FoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/': {
      id: '/hosted/'
      path: '/'
      fullPath: '/hosted/'
      preLoaderRoute: typeof HostedIndexRouteImport
      parentRoute: typeof HostedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted/tickets': {
      id: '/hosted/tickets'
      path: '/tickets'
      fullPath: '/hosted/tickets'
      preLoaderRoute: typeof HostedTicketsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/team': {
      id: '/hosted/team'
      path: '/team'
      fullPath: '/hosted/team'
      preLoaderRoute: typeof HostedTeamRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/settings': {
      id: '/hosted/settings'
      path: '/settings'
      fullPath: '/hosted/settings'
      preLoaderRoute: typeof HostedSettingsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/request-funds': {
      id: '/hosted/request-funds'
      path: '/request-funds'
      fullPath: '/hosted/request-funds'
      preLoaderRoute: typeof HostedRequestFundsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/perks-hub': {
      id: '/hosted/perks-hub'
      path: '/perks-hub'
      fullPath: '/hosted/perks-hub'
      preLoaderRoute: typeof HostedPerksHubRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/faq': {
      id: '/hosted/faq'
      path: '/faq'
      fullPath: '/hosted/faq'
      preLoaderRoute: typeof HostedFaqRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/applications': {
      id: '/hosted/applications'
      path: '/applications'
      fullPath: '/hosted/applications'
      preLoaderRoute: typeof HostedApplicationsRouteImport
      parentRoute: typeof HostedRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage-perks': {
      id: '/admin/storage-perks'
      path: '/storage-perks'
      fullPath: '/admin/storage-perks'
      preLoaderRoute: typeof AdminStoragePerksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hosted/perks/storage': {
      id: '/hosted/perks/storage'
      path: '/perks/storage'
      fullPath: '/hosted/perks/storage'
      preLoaderRoute: typeof HostedPerksStorageRouteImport
      parentRoute: typeof HostedRoute
    }
    '/hosted/perks/storage/upload': {
      id: '/hosted/perks/storage/upload'
      path: '/upload'
      fullPath: '/hosted/perks/storage/upload'
      preLoaderRoute: typeof HostedPerksStorageUploadRouteImport
      parentRoute: typeof HostedPerksStorageRoute
    }
    '/hosted/perks/storage/limits': {
      id: '/hosted/perks/storage/limits'
      path: '/limits'
      fullPath: '/hosted/perks/storage/limits'
      preLoaderRoute: typeof HostedPerksStorageLimitsRouteImport
      parentRoute: typeof HostedPerksStorageRoute
    }
    '/hosted/perks/storage/explorer': {
      id: '/hosted/perks/storage/explorer'
      path: '/explorer'
      fullPath: '/hosted/perks/storage/explorer'
      preLoaderRoute: typeof HostedPerksStorageExplorerRouteImport
      parentRoute: typeof HostedPerksStorageRoute
    }
    '/hosted/perks/storage/cdn': {
      id: '/hosted/perks/storage/cdn'
      path: '/cdn'
      fullPath: '/hosted/perks/storage/cdn'
      preLoaderRoute: typeof HostedPerksStorageCdnRouteImport
      parentRoute: typeof HostedPerksStorageRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminStoragePerksRoute: typeof AdminStoragePerksRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminStoragePerksRoute: AdminStoragePerksRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HostedPerksStorageRouteChildren {
  HostedPerksStorageCdnRoute: typeof HostedPerksStorageCdnRoute
  HostedPerksStorageExplorerRoute: typeof HostedPerksStorageExplorerRoute
  HostedPerksStorageLimitsRoute: typeof HostedPerksStorageLimitsRoute
  HostedPerksStorageUploadRoute: typeof HostedPerksStorageUploadRoute
}

const HostedPerksStorageRouteChildren: HostedPerksStorageRouteChildren = {
  HostedPerksStorageCdnRoute: HostedPerksStorageCdnRoute,
  HostedPerksStorageExplorerRoute: HostedPerksStorageExplorerRoute,
  HostedPerksStorageLimitsRoute: HostedPerksStorageLimitsRoute,
  HostedPerksStorageUploadRoute: HostedPerksStorageUploadRoute,
}

const HostedPerksStorageRouteWithChildren =
  HostedPerksStorageRoute._addFileChildren(HostedPerksStorageRouteChildren)

interface HostedRouteChildren {
  HostedApplicationsRoute: typeof HostedApplicationsRoute
  HostedFaqRoute: typeof HostedFaqRoute
  HostedPerksHubRoute: typeof HostedPerksHubRoute
  HostedRequestFundsRoute: typeof HostedRequestFundsRoute
  HostedSettingsRoute: typeof HostedSettingsRoute
  HostedTeamRoute: typeof HostedTeamRoute
  HostedTicketsRoute: typeof HostedTicketsRoute
  HostedIndexRoute: typeof HostedIndexRoute
  HostedPerksStorageRoute: typeof HostedPerksStorageRouteWithChildren
}

const HostedRouteChildren: HostedRouteChildren = {
  HostedApplicationsRoute: HostedApplicationsRoute,
  HostedFaqRoute: HostedFaqRoute,
  HostedPerksHubRoute: HostedPerksHubRoute,
  HostedRequestFundsRoute: HostedRequestFundsRoute,
  HostedSettingsRoute: HostedSettingsRoute,
  HostedTeamRoute: HostedTeamRoute,
  HostedTicketsRoute: HostedTicketsRoute,
  HostedIndexRoute: HostedIndexRoute,
  HostedPerksStorageRoute: HostedPerksStorageRouteWithChildren,
}

const HostedRouteWithChildren =
  HostedRoute._addFileChildren(HostedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  FoundaryRoute: FoundaryRoute,
  HostedRoute: HostedRouteWithChildren,
  InviteRegisterRoute: InviteRegisterRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TosRoute: TosRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
